// Single source of truth for the columns the app writes to wardrobe_responses.
// The schema-contract test asserts buildSupabaseRows() emits EXACTLY these keys.
// Keep in sync with utils/supabase/create_table.sql.
export const DB_COLUMNS = [
  'session_id',
  'completed_at',
  'wardrobe_size',
  'shopping_frequency',
  'disposal_habit',
  'primary_driver',
  'persona',
  'social_value',
  'emotional_value',
  'functional_value',
  'inflow_outflow_value',
  'set_type',
  'garment_type',
  'consent_given',
  'consent_timestamp',
  'completion_status',
  'how_got',
  'cost',
  'wear_frequency',
  'main_use',
  'main_use_other',
  'why_bought',
  'why_bought_other',
  'how_long_had',
  'why_favorite',
  'why_favorite_other',
  'wash_frequency',
  'repaired',
  'why_not_wear',
  'why_not_wear_other',
  'disposal_plan',
  'how_long_had_years',
] as const;
